"""Add delivery fields to Order

Revision ID: 0e2d19b82189
Revises: bfb8f919c48a
Create Date: 2026-02-13 01:47:44.974837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2d19b82189'
down_revision: Union[str, Sequence[str], None] = 'bfb8f919c48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contact_info', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'zip_code')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'last_name')
    op.drop_column('orders', 'first_name')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'contact_info')
    # ### end Alembic commands ###
