"""Add BadWord model and is_flagged

Revision ID: 53047893116c
Revises: 0e2d19b82189
Create Date: 2026-02-19 21:03:01.480280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53047893116c'
down_revision: Union[str, Sequence[str], None] = '0e2d19b82189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('is_flagged', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'is_flagged')
    # ### end Alembic commands ###
